# This is a basic workflow to help you get started with Actions

name: Test then Deploy Client (Temp No Deploy)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths: 'client/**'
  pull_request:
    branches: [ master ]
    paths: 'client/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Packages
      run: npm install
      working-directory: client

    - name: Build page
      run: npm run build
      working-directory: client

    - name: Run Tests
      run: npm run test
      working-directory: client    

  # Deploy:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
  #   needs: test
  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #   - uses: actions/checkout@v2

  #   - name: Install Packages
  #     run: npm install
  #     working-directory: client

  #   - name: Build page
  #     run: npm run build
  #     working-directory: client
    
  #   - name: Initialize Google Cloud SDK
  #     uses: zxyle/publish-gae-action@master
  #     with:
  #       service_account_email: ${{ secrets.GCP_FE_SA_EMAIL }}
  #       service_account_key: ${{ secrets.GCP_FE_SA_KEY }}
  #       project_id: ${{ secrets.FE_PROJECT_ID }}

  #   - name: Publish app to Google App Engine
  #     run: |
  #       # This client-secret.json is converted by GCP_FE_SA_KEY.
  #       gcloud auth activate-service-account ${{ secrets.GCP_FE_SA_EMAIL }} --key-file=client-secret.json
  #       gcloud config set project ${{ secrets.FE_PROJECT_ID }}
  #       gcloud -q app deploy ./client/app.yaml --promote
